### ISSUE TITLE
How do we create a "prototype" component set

### ISSUE THREAD

**Issue by JedWatson** [css-components/comparison#7]
Would be good to get a prototype implementation in place first with the simplest / easiest-to-replace solution we can think of.

Not sure if there's a way realistically to extend it in the framework examples, but ideally each implementation concentrates on _just_ the styling differences and is otherwise equivalent.

**Comment by mxstbr** [comment]
I was thinking of structuring it like this:

``` Sh
comparisons
- examples         # examples of specific methodologies
  - aphrodite
    - common       # same files for all methodologies, maybe slightly different build process
      - components
      - config
    - components   # components that'll have differences
      - NavBar.js
      - NavItem.js
  - jss
    - common
    - components
  - css-modules
  - etc
```

**Comment by mxstbr** [comment]
@MicheleBertoli totally took care of that and made it a great setup in #10, will now factor out all the common stuff (babelrc, eslintrc, utils) to a shared folder for all examples to use!
